### ISSUE TITLE
SyntaxError when trying to run gulp

### ISSUE THREAD

**Issue by SuperKieran** [gokulkrishh/React-hacker-news#5]
I get error : SyntaxError when running gulp in the console.

``` bash
events.js:154
      throw er; // Unhandled 'error' event
      ^

SyntaxError: /Users/admin/code/react/web/React-hacker-news/app/js/app.jsx: Unexpected token (20:6)
  18 |   render() {
  19 |     return (
> 20 |       <div className="header"></div>
     |       ^
  21 |     );
  22 |   }
  23 | });
    at Parser.pp.raise (/Users/admin/code/react/web/React-hacker-news/node_modules/babelify/node_modules/babylon/index.js:1378:13)
    at Parser.pp.unexpected (/Users/admin/code/react/web/React-hacker-news/node_modules/babelify/node_modules/babylon/index.js:2817:8)
    at Parser.pp.parseExprAtom (/Users/admin/code/react/web/React-hacker-news/node_modules/babelify/node_modules/babylon/index.js:749:12)
    at Parser.pp.parseExprSubscripts (/Users/admin/code/react/web/React-hacker-news/node_modules/babelify/node_modules/babylon/index.js:504:19)
    at Parser.pp.parseMaybeUnary (/Users/admin/code/react/web/React-hacker-news/node_modules/babelify/node_modules/babylon/index.js:484:19)
    at Parser.pp.parseExprOps (/Users/admin/code/react/web/React-hacker-news/node_modules/babelify/node_modules/babylon/index.js:415:19)
    at Parser.pp.parseMaybeConditional (/Users/admin/code/react/web/React-hacker-news/node_modules/babelify/node_modules/babylon/index.js:397:19)
    at Parser.pp.parseMaybeAssign (/Users/admin/code/react/web/React-hacker-news/node_modules/babelify/node_modules/babylon/index.js:360:19)
    at Parser.pp.parseParenAndDistinguishExpression (/Users/admin/code/react/web/React-hacker-news/node_modules/babelify/node_modules/babylon/index.js:822:26)
    at Parser.pp.parseExprAtom (/Users/admin/code/react/web/React-hacker-news/node_modules/babelify/node_modules/babylon/index.js:708:19)
```

**Comment by gokulkrishh** [comment]
@SuperKieran This is coming from `babelify`. Can you delete node_modules folder in the project and try to do `npm install` again.

**Comment by SuperKieran** [comment]
@gokulkrishh I delete node_modules folder in the project and try to do npm install again. But the Error still exists. :(

**Comment by gokulkrishh** [comment]
@SuperKieran Strange. I am not getting this error.

**Comment by SuperKieran** [comment]
I fixed it with this:

```
.transform("babelify", {presets: ["es2015", "react"]})
```

And... What react version do you use?(You forgot to write in package.json?)

**Comment by gokulkrishh** [comment]
Awesome!!
